### ISSUE TITLE
Why does create_data_splits.py discard the first return value train_folds of the create_cv_folds function and only keep val_folds?

### ISSUE THREAD

**Issue by mbybtjh** [dslaborg/sumo#10]

**Comment by n-grieger** [comment]
Hi @mbybtjh, we can discard the train_folds because they can be reconstructed from the val_folds, e.g., the train_folds of fold 0 are the val_folds of folds 1-5. By discarding the train_folds and not saving them to disk, we save memory.

**Comment by mbybtjh** [comment]
Thanks for your reply!
