### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by meniua** [dslaborg/sumo#8]
Hello, could you please tell me the specific format of MASS data used in training SUMO model? (I have applied for MASS data set, and I am replicating some code based on MASS data set)

**Comment by n-grieger** [comment]
Hi @meniua,

I'm sorry for the very late reply. Unfortunately, the main developer of SUMO is no longer with our team, and I only recently noticed your message. I hope you still find this information useful.

As far as I understand, the relevant part of the MASS dataset was first preprocessed/extracted using the MODA repository: https://github.com/klacourse/MODA_GC. Afterward, the `create_data_splits.py` script was used to prepare the data for training SUMO. This script is available in the `scripts` folder.
