### ISSUE TITLE
How to handle artifacts using SUMO?

### ISSUE THREAD

**Issue by klacourse** [dslaborg/sumo#9]
Hello, I'm wondering how to handle artifacts with the use of SUMO.

I understand that SUMO was trained only on clean data.

Would it be valid to first run the SUMO detector on all N2 stages of a recording and then exclude all the spindles occurring during an artifact? Can a huge artifact corrupt how SUMO detects the spindle on clean data near the artifact?

If I need to provide only clean data to SUMO: Does SUMO need 115s of clean data to work properly? On the GitHub you provided as demo data a single 30s epoch, so it looks like we can use SUMO properly with a shorter amount of data (I mean shorter than 115s). What is the minimum signal duration we can use to run SUMO on? This is important if we need to extract only clean segments.

Thank you !

**Comment by n-grieger** [comment]
Hi @klacourse,

I'm sorry for the very late reply. Unfortunately, the main developer of SUMO is no longer with our team, and I only recently noticed your message. I hope you still find this information useful.

> Would it be valid to first run the SUMO detector on all N2 stages of a recording and then exclude all the spindles occurring during an artifact? Can a huge artifact corrupt how SUMO detects the spindle on clean data near the artifact?

Yes, SUMO is affected by high amplitude artifacts. If the artifact is too large, it will likely affect data normalization during preprocessing and reduce the number of spindles detected. I recommend to clean/remove artifacts first and then identify sleep spindles on N2 stages using SUMO.

> If I need to provide only clean data to SUMO: Does SUMO need 115s of clean data to work properly? On the GitHub you provided as demo data a single 30s epoch, so it looks like we can use SUMO properly with a shorter amount of data (I mean shorter than 115s). What is the minimum signal duration we can use to run SUMO on? This is important if we need to extract only clean segments.

In theory, SUMO works on any duration of data. However, the neural network has a receptive field of about 4.5 seconds, i.e., the model uses up to the last 2.25 seconds and up to the next 2.25 seconds to make a prediction for a datapoint. In other words, data at the beginning (the first 2.25 seconds) or the end (the last 2.25 seconds) of a signal will not have the full context of data available for optimal prediction. We recommend using at least 30 seconds of data to ensure that the model has enough context to accurately predict spindles.

Best wishes!
